---
params:
  start_time: "12:00pm PT"
  duration: 42
---

## Growth Mindset & GitHub for Publishing • `r kyber:::fmt_duration(params$start_time, params$duration)`

* **Intro to GitHub, edits & publishing** ([slides](https://docs.google.com/presentation/d/1geUN-dv-NMx6IgeCwMRVmTO8nZaauIl26tZDOrkLW_E/) 1-13) (16 min) – Julie
  -  ‎
  -
  - 
* **Breakout groups: practice editing & committing** (10 min) (<font color="red">pause recording</font>) –  Stef (breakout random groups of 3)
* *This first breakout group can be less collaborative and more co-working...but please chat and screenshare!*

  - Our cohort repo: <`r params_registry$github_repo`>
  - Edit & commit your file, and talk with your breakout group!
    - Go to our cohort repo, navigate > github-clinic > yourname.md
    - Click on the pencil to edit your file
    - Make small edits and commit with a commit message
    - Github.com will give you a default message but get into the habit of writing an actual message to yourself/others (breadcrumbs)
  - Learn anything cool? Share!  
  - ‎
  -
  - (<font color="red">resume recording</font>)
* **Regroup, collaborating and publishing** ([slides](https://docs.google.com/presentation/d/1geUN-dv-NMx6IgeCwMRVmTO8nZaauIl26tZDOrkLW_E/) 14-16) (5 min) – Julie screenshare
  - ‎
  -
* **Discussion and screenshares** (10 min)
  - ‎
  -
  -
