---
params:
  start_time: "1:30pm PT"
  duration: 45
---

## Growth Mindset & GitHub for Publishing • `r kyber:::fmt_duration(params$start_time, params$duration)`

-   **Intro to GitHub, edits & publishing** (slides 1-18) (25 min) – Anna

    -   ‎
    -   
    -   

-   **Confirm GitHub access** - if anyone is having problems with access, let us know *before entering your breakout room*.

-   **Breakout groups** (15 min) - Random groups of \~3 [9-10 Rooms] - [ Mentor Name ] (<font color="red">pause recording</font>)

    -   **Prompt: practice editing & committing**
    -   *This breakout group can be less collaborative and more co-working...but please chat and screenshare!*
    -   Our cohort repo: \<`r params_registry$github_repo`\>
    -   Edit & commit your file, and talk with your breakout group!
        -   Go to our cohort repo, navigate \> github-clinic \> yourname.md
        -   Click on the pencil to edit your file
        -   Make small edits and commit with a commit message
        -   Github.com will give you a default message but get into the habit of writing an actual message to yourself/others (breadcrumbs)
        -   Committing is different from saving (cancel if you save!)
    -   
    -   ‎
    -   
    -   ‎
    -   
    -   

    (<font color="red">resume recording</font>)

-   **Regroup, discussion and screenshares** ([slides](https://docs.google.com/presentation/d/1geUN-dv-NMx6IgeCwMRVmTO8nZaauIl26tZDOrkLW_E/) 19-20) (5 min) – Anna screenshare

    -   *Learn anything cool? Share with us!*
    -   
    -   ‎
    -   
    -   ‎
    -   
    -   

-   **Useful Resources:**

    -   CA Waterboards data center <https://github.com/CAWaterBoardDataCenter> 
