---
params:
  start_time: "1:30pm PT"
  duration: 0
---

-   **Announcements** (please contribute!)
    -   ‎
    -   
    -   
-   **Requests for peer-assists** (please share what you need and/or how you can assist!)
    -   ‎
    -   
    -   
-   **Connecting between Cohort Calls**
    -   *Connect with your team*
        -   Your Seaside Chats!
    -   *Connect with others in your cohort*
        -   <!--- Cohort GitHub Repo: `r params$repo` --->

            -   details, links, issues

        -   Chat using your cohort's channel in the Water Boards Openscapes Team (see below)
    -   *Connect with other Water Boards Openscapes Cohorts*
        -   [Microsoft Teams - Openscapes Team](https://teams.microsoft.com/l/team/19%3ahddOcIDOdB9XVRDG0aaHsl9icCtjZrQpgnCuONoAYaU1%40thread.tacv2/conversations?groupId=d20bd7eb-287d-4c0e-8200-be28810f6112&tenantId=fe186a25-7d49-41e6-9941-05d2281d36c1) -- We already sent an invite to contribute to the Openscapes Channel! If you didn’t receive it or you need another invite, please let us know. 
        -   Call Digest will be sent next week (via MS Teams Chat to [2024-SWRCB-Sp] Channel)
-   **Resources** available for reuse/remix
    -   Water Boards MS Team - Data Community - If you aren’t already in the community, learn how to sign up [here](https://www.waterboards.ca.gov/resources/oima/cowi/data_communities.html)!
    -   [openscapes.org](https://openscapes.org)
        -   [/series](https://openscapes.github.io/series): Champions program lesson series
        -   [/media](https://openscapes.org/media): slide decks, publications, media
        -   [/blog](https://openscapes.org/blog): stories from the community
    -   github: [\@openscapes](https://github.com/openscapes)
        -   [how_we_work](https://github.com/Openscapes/how_we_work), [seaside-chats](https://github.com/Openscapes/seaside-chats): Examples from previous cohorts
    -   Mastodon: [fosstodon.org/\@openscapes](https://fosstodon.org/@openscapes)
    -   artwork: by the amazing [Allison Horst](https://twitter.com/allison_horst)
-   **Feedback on this session**
    -   What worked? What didn’t? What surprised you? What would you change?
        -   ‎
        -   
        -   

Thank you, see you next time!
