---
params: 
  start_time: "12:00pm PT"
  duration: 4
---

## Welcome • `r kyber:::fmt_duration(params$start_time, params$duration)`

- **Welcome to Openscapes! 👋** (2 min) – Julie
  - <font color="red">We are now recording this meeting.</font> 
  - <font color="red">Live transcriptions are available.</font>
  - CoC Reminder ([full version](https://www.openscapes.org/code-of-conduct/))
    - Be respectful and value each other’s ideas, styles and viewpoints.
    - Be direct but professional; we cannot withhold hard truths.
    - Be inclusive and help new perspectives be heard.
    - Be open to learning from others.
    - Lead by example and match your actions with your words.
  - **Our team here on this call:** 
    - Julie Lowndes / Openscapes
    - Stefanie Butland / Openscapes
    - Ileana Fenwick / Openscapes
    - Andy Teucher / Openscapes
    - Openscapes Mentors - huge expertise; they can share and help answer questions
  
- **Today’s goals** (1 min) – Julie
  - 
  -


- **Followups** (1 min) – Julie
- Call 2: Overwhelm is real, we’re all making progress
    - Providing some structure (space & place) for you to explore new ideas and habits
      - Seaside Chats - time to be intentional to develop goals and habits       - Co-working - a different way to do work you’re doing anyhow
      - Pathways Sheets - an intentional way to reflect on workflows. Developed in our shared folder - look at other people’s
  - Potentially increase 5 mins here.
- Call 3: GROUP PHOTO!
  - ‎
  - 

- **Questions** before we get started?
  - ‎
  - 